CREATE DATABASE IF NOT EXIST guestbook CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE guestbook;

CREATE TABLE IF NOT EXIST messages {
    id UNT AUTO_INCRIMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
};